###
POST http://localhost:3000/api/technicians/register
Content-Type: application/json

{
  "username": "loading1",
  "password": "asdasda1",
  "name": "sy",
  "jobType": "漆工",
  "hourlyRate": 50,
  "contactInfo": "137",
  "income": 0
}

###
POST http://localhost:3000/api/technicians/register
Content-Type: application/json

{
  "username": "loading2",
  "password": "asdasda1",
  "name": "sy",
  "jobType": "漆工",
  "hourlyRate": 50,
  "contactInfo": "137",
  "income": 0
}
###
POST http://localhost:3000/api/technicians/login
Content-Type: application/json

{
  "username": "loading1",
  "password": "asdasda1"
}

###
GET http://localhost:3000/api/technicians/1
###
PUT http://localhost:3000/api/technicians/1/work-orders/1/1/updateStatus
Content-Type: application/json

{
  "action": "accept"
}

###
PUT http://localhost:3000/api/technicians/1/work-orders/1/progress
Content-Type: application/json

{
    "progress": 1 ,
    "description": "做完了"
}

###
###
POST http://localhost:3000/api/technicians/1/work-orders/1/materials
Content-Type: application/json

{
  "materialId": 0,
  "workOrderId": 1,
  "materialName": "wood",
  "quantity": 2,
  "unitPrice": 0.9,
  "totalPrice": 0.45
}

###
GET http://localhost:3000/api/technicians/1/repair-records

###
GET http://localhost:3000/api/technicians/1/notifications

###
GET http://localhost:3000/api/technicians/1/work-orders